language: python
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls[yaml]
script:
  - flake8
  - nosetests --with-coverage
after_success:
  - coveralls
env:
  - OCTOPART_API_KEY=a8cfd5a0
